
apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index-app
  template:
    metadata:
      labels:
        app: index-app
    spec:
      containers:
      - name: index-ctn
        image: myoli999/index-app:1.0  
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"
